# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/poulin/Documents/Labo/ProgrammeCosmicRays/antiprotons

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/poulin/Documents/Labo/ProgrammeCosmicRays/antiprotons

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/poulin/Documents/Labo/ProgrammeCosmicRays/antiprotons/CMakeFiles /Users/poulin/Documents/Labo/ProgrammeCosmicRays/antiprotons/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/poulin/Documents/Labo/ProgrammeCosmicRays/antiprotons/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build/executable

# Build rule for target.
build/executable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/executable
.PHONY : build/executable

# fast build rule for target.
build/executable/fast:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/build
.PHONY : build/executable/fast

MAIN.o: MAIN.c.o

.PHONY : MAIN.o

# target to build an object file
MAIN.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/MAIN.c.o
.PHONY : MAIN.c.o

MAIN.i: MAIN.c.i

.PHONY : MAIN.i

# target to preprocess a source file
MAIN.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/MAIN.c.i
.PHONY : MAIN.c.i

MAIN.s: MAIN.c.s

.PHONY : MAIN.s

# target to generate assembly for a file
MAIN.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/MAIN.c.s
.PHONY : MAIN.c.s

sources/ANTI_PROTON.o: sources/ANTI_PROTON.c.o

.PHONY : sources/ANTI_PROTON.o

# target to build an object file
sources/ANTI_PROTON.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/ANTI_PROTON.c.o
.PHONY : sources/ANTI_PROTON.c.o

sources/ANTI_PROTON.i: sources/ANTI_PROTON.c.i

.PHONY : sources/ANTI_PROTON.i

# target to preprocess a source file
sources/ANTI_PROTON.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/ANTI_PROTON.c.i
.PHONY : sources/ANTI_PROTON.c.i

sources/ANTI_PROTON.s: sources/ANTI_PROTON.c.s

.PHONY : sources/ANTI_PROTON.s

# target to generate assembly for a file
sources/ANTI_PROTON.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/ANTI_PROTON.c.s
.PHONY : sources/ANTI_PROTON.c.s

sources/BESSEL_PRELIM.o: sources/BESSEL_PRELIM.c.o

.PHONY : sources/BESSEL_PRELIM.o

# target to build an object file
sources/BESSEL_PRELIM.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/BESSEL_PRELIM.c.o
.PHONY : sources/BESSEL_PRELIM.c.o

sources/BESSEL_PRELIM.i: sources/BESSEL_PRELIM.c.i

.PHONY : sources/BESSEL_PRELIM.i

# target to preprocess a source file
sources/BESSEL_PRELIM.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/BESSEL_PRELIM.c.i
.PHONY : sources/BESSEL_PRELIM.c.i

sources/BESSEL_PRELIM.s: sources/BESSEL_PRELIM.c.s

.PHONY : sources/BESSEL_PRELIM.s

# target to generate assembly for a file
sources/BESSEL_PRELIM.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/BESSEL_PRELIM.c.s
.PHONY : sources/BESSEL_PRELIM.c.s

sources/CROSS_SECTIONS.o: sources/CROSS_SECTIONS.c.o

.PHONY : sources/CROSS_SECTIONS.o

# target to build an object file
sources/CROSS_SECTIONS.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/CROSS_SECTIONS.c.o
.PHONY : sources/CROSS_SECTIONS.c.o

sources/CROSS_SECTIONS.i: sources/CROSS_SECTIONS.c.i

.PHONY : sources/CROSS_SECTIONS.i

# target to preprocess a source file
sources/CROSS_SECTIONS.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/CROSS_SECTIONS.c.i
.PHONY : sources/CROSS_SECTIONS.c.i

sources/CROSS_SECTIONS.s: sources/CROSS_SECTIONS.c.s

.PHONY : sources/CROSS_SECTIONS.s

# target to generate assembly for a file
sources/CROSS_SECTIONS.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/CROSS_SECTIONS.c.s
.PHONY : sources/CROSS_SECTIONS.c.s

sources/DIFFUSION_PROPAGATION.o: sources/DIFFUSION_PROPAGATION.c.o

.PHONY : sources/DIFFUSION_PROPAGATION.o

# target to build an object file
sources/DIFFUSION_PROPAGATION.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/DIFFUSION_PROPAGATION.c.o
.PHONY : sources/DIFFUSION_PROPAGATION.c.o

sources/DIFFUSION_PROPAGATION.i: sources/DIFFUSION_PROPAGATION.c.i

.PHONY : sources/DIFFUSION_PROPAGATION.i

# target to preprocess a source file
sources/DIFFUSION_PROPAGATION.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/DIFFUSION_PROPAGATION.c.i
.PHONY : sources/DIFFUSION_PROPAGATION.c.i

sources/DIFFUSION_PROPAGATION.s: sources/DIFFUSION_PROPAGATION.c.s

.PHONY : sources/DIFFUSION_PROPAGATION.s

# target to generate assembly for a file
sources/DIFFUSION_PROPAGATION.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/DIFFUSION_PROPAGATION.c.s
.PHONY : sources/DIFFUSION_PROPAGATION.c.s

sources/GAUSSJ.o: sources/GAUSSJ.c.o

.PHONY : sources/GAUSSJ.o

# target to build an object file
sources/GAUSSJ.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/GAUSSJ.c.o
.PHONY : sources/GAUSSJ.c.o

sources/GAUSSJ.i: sources/GAUSSJ.c.i

.PHONY : sources/GAUSSJ.i

# target to preprocess a source file
sources/GAUSSJ.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/GAUSSJ.c.i
.PHONY : sources/GAUSSJ.c.i

sources/GAUSSJ.s: sources/GAUSSJ.c.s

.PHONY : sources/GAUSSJ.s

# target to generate assembly for a file
sources/GAUSSJ.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/GAUSSJ.c.s
.PHONY : sources/GAUSSJ.c.s

sources/HELIUM.o: sources/HELIUM.c.o

.PHONY : sources/HELIUM.o

# target to build an object file
sources/HELIUM.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/HELIUM.c.o
.PHONY : sources/HELIUM.c.o

sources/HELIUM.i: sources/HELIUM.c.i

.PHONY : sources/HELIUM.i

# target to preprocess a source file
sources/HELIUM.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/HELIUM.c.i
.PHONY : sources/HELIUM.c.i

sources/HELIUM.s: sources/HELIUM.c.s

.PHONY : sources/HELIUM.s

# target to generate assembly for a file
sources/HELIUM.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/HELIUM.c.s
.PHONY : sources/HELIUM.c.s

sources/PRIMARY_PBAR.o: sources/PRIMARY_PBAR.c.o

.PHONY : sources/PRIMARY_PBAR.o

# target to build an object file
sources/PRIMARY_PBAR.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PRIMARY_PBAR.c.o
.PHONY : sources/PRIMARY_PBAR.c.o

sources/PRIMARY_PBAR.i: sources/PRIMARY_PBAR.c.i

.PHONY : sources/PRIMARY_PBAR.i

# target to preprocess a source file
sources/PRIMARY_PBAR.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PRIMARY_PBAR.c.i
.PHONY : sources/PRIMARY_PBAR.c.i

sources/PRIMARY_PBAR.s: sources/PRIMARY_PBAR.c.s

.PHONY : sources/PRIMARY_PBAR.s

# target to generate assembly for a file
sources/PRIMARY_PBAR.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PRIMARY_PBAR.c.s
.PHONY : sources/PRIMARY_PBAR.c.s

sources/PROTON.o: sources/PROTON.c.o

.PHONY : sources/PROTON.o

# target to build an object file
sources/PROTON.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PROTON.c.o
.PHONY : sources/PROTON.c.o

sources/PROTON.i: sources/PROTON.c.i

.PHONY : sources/PROTON.i

# target to preprocess a source file
sources/PROTON.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PROTON.c.i
.PHONY : sources/PROTON.c.i

sources/PROTON.s: sources/PROTON.c.s

.PHONY : sources/PROTON.s

# target to generate assembly for a file
sources/PROTON.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/PROTON.c.s
.PHONY : sources/PROTON.c.s

sources/SOLAR_MOD.o: sources/SOLAR_MOD.c.o

.PHONY : sources/SOLAR_MOD.o

# target to build an object file
sources/SOLAR_MOD.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/SOLAR_MOD.c.o
.PHONY : sources/SOLAR_MOD.c.o

sources/SOLAR_MOD.i: sources/SOLAR_MOD.c.i

.PHONY : sources/SOLAR_MOD.i

# target to preprocess a source file
sources/SOLAR_MOD.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/SOLAR_MOD.c.i
.PHONY : sources/SOLAR_MOD.c.i

sources/SOLAR_MOD.s: sources/SOLAR_MOD.c.s

.PHONY : sources/SOLAR_MOD.s

# target to generate assembly for a file
sources/SOLAR_MOD.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/SOLAR_MOD.c.s
.PHONY : sources/SOLAR_MOD.c.s

sources/TRIDAG.o: sources/TRIDAG.c.o

.PHONY : sources/TRIDAG.o

# target to build an object file
sources/TRIDAG.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/TRIDAG.c.o
.PHONY : sources/TRIDAG.c.o

sources/TRIDAG.i: sources/TRIDAG.c.i

.PHONY : sources/TRIDAG.i

# target to preprocess a source file
sources/TRIDAG.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/TRIDAG.c.i
.PHONY : sources/TRIDAG.c.i

sources/TRIDAG.s: sources/TRIDAG.c.s

.PHONY : sources/TRIDAG.s

# target to generate assembly for a file
sources/TRIDAG.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/TRIDAG.c.s
.PHONY : sources/TRIDAG.c.s

sources/besselj0_next.o: sources/besselj0_next.c.o

.PHONY : sources/besselj0_next.o

# target to build an object file
sources/besselj0_next.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj0_next.c.o
.PHONY : sources/besselj0_next.c.o

sources/besselj0_next.i: sources/besselj0_next.c.i

.PHONY : sources/besselj0_next.i

# target to preprocess a source file
sources/besselj0_next.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj0_next.c.i
.PHONY : sources/besselj0_next.c.i

sources/besselj0_next.s: sources/besselj0_next.c.s

.PHONY : sources/besselj0_next.s

# target to generate assembly for a file
sources/besselj0_next.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj0_next.c.s
.PHONY : sources/besselj0_next.c.s

sources/besselj1_next.o: sources/besselj1_next.c.o

.PHONY : sources/besselj1_next.o

# target to build an object file
sources/besselj1_next.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj1_next.c.o
.PHONY : sources/besselj1_next.c.o

sources/besselj1_next.i: sources/besselj1_next.c.i

.PHONY : sources/besselj1_next.i

# target to preprocess a source file
sources/besselj1_next.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj1_next.c.i
.PHONY : sources/besselj1_next.c.i

sources/besselj1_next.s: sources/besselj1_next.c.s

.PHONY : sources/besselj1_next.s

# target to generate assembly for a file
sources/besselj1_next.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/besselj1_next.c.s
.PHONY : sources/besselj1_next.c.s

sources/nrutil.o: sources/nrutil.c.o

.PHONY : sources/nrutil.o

# target to build an object file
sources/nrutil.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/nrutil.c.o
.PHONY : sources/nrutil.c.o

sources/nrutil.i: sources/nrutil.c.i

.PHONY : sources/nrutil.i

# target to preprocess a source file
sources/nrutil.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/nrutil.c.i
.PHONY : sources/nrutil.c.i

sources/nrutil.s: sources/nrutil.c.s

.PHONY : sources/nrutil.s

# target to generate assembly for a file
sources/nrutil.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/nrutil.c.s
.PHONY : sources/nrutil.c.s

sources/spectra.o: sources/spectra.c.o

.PHONY : sources/spectra.o

# target to build an object file
sources/spectra.c.o:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/spectra.c.o
.PHONY : sources/spectra.c.o

sources/spectra.i: sources/spectra.c.i

.PHONY : sources/spectra.i

# target to preprocess a source file
sources/spectra.c.i:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/spectra.c.i
.PHONY : sources/spectra.c.i

sources/spectra.s: sources/spectra.c.s

.PHONY : sources/spectra.s

# target to generate assembly for a file
sources/spectra.c.s:
	$(MAKE) -f CMakeFiles/build/executable.dir/build.make CMakeFiles/build/executable.dir/sources/spectra.c.s
.PHONY : sources/spectra.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... build/executable"
	@echo "... MAIN.o"
	@echo "... MAIN.i"
	@echo "... MAIN.s"
	@echo "... sources/ANTI_PROTON.o"
	@echo "... sources/ANTI_PROTON.i"
	@echo "... sources/ANTI_PROTON.s"
	@echo "... sources/BESSEL_PRELIM.o"
	@echo "... sources/BESSEL_PRELIM.i"
	@echo "... sources/BESSEL_PRELIM.s"
	@echo "... sources/CROSS_SECTIONS.o"
	@echo "... sources/CROSS_SECTIONS.i"
	@echo "... sources/CROSS_SECTIONS.s"
	@echo "... sources/DIFFUSION_PROPAGATION.o"
	@echo "... sources/DIFFUSION_PROPAGATION.i"
	@echo "... sources/DIFFUSION_PROPAGATION.s"
	@echo "... sources/GAUSSJ.o"
	@echo "... sources/GAUSSJ.i"
	@echo "... sources/GAUSSJ.s"
	@echo "... sources/HELIUM.o"
	@echo "... sources/HELIUM.i"
	@echo "... sources/HELIUM.s"
	@echo "... sources/PRIMARY_PBAR.o"
	@echo "... sources/PRIMARY_PBAR.i"
	@echo "... sources/PRIMARY_PBAR.s"
	@echo "... sources/PROTON.o"
	@echo "... sources/PROTON.i"
	@echo "... sources/PROTON.s"
	@echo "... sources/SOLAR_MOD.o"
	@echo "... sources/SOLAR_MOD.i"
	@echo "... sources/SOLAR_MOD.s"
	@echo "... sources/TRIDAG.o"
	@echo "... sources/TRIDAG.i"
	@echo "... sources/TRIDAG.s"
	@echo "... sources/besselj0_next.o"
	@echo "... sources/besselj0_next.i"
	@echo "... sources/besselj0_next.s"
	@echo "... sources/besselj1_next.o"
	@echo "... sources/besselj1_next.i"
	@echo "... sources/besselj1_next.s"
	@echo "... sources/nrutil.o"
	@echo "... sources/nrutil.i"
	@echo "... sources/nrutil.s"
	@echo "... sources/spectra.o"
	@echo "... sources/spectra.i"
	@echo "... sources/spectra.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

